theme: jekyll-theme-minimal
logo: docs/assets/Profile01_resized_IMG_20251009_135706.jpg
title: David Salas Herrera
description: Â¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Analisis de Datos.
